/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utils;
import Services.crudTerrain;
import Entities.Terrain;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.util.Date;
import java.util.List;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
//import javax.swing.text.Document;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.util.Date;
import static javax.print.DocFlavor.BYTE_ARRAY.PDF;
import static javax.print.DocFlavor.INPUT_STREAM.PDF;


/**
 *
 * @author Cyrine
 */
public class PDFTerrain {
    

/**
 *
 * @author cyrine
 */


 public void pdfGeneration() throws FileNotFoundException, DocumentException, MalformedURLException, IOException, URISyntaxException {
        Document document = new Document();
        crudTerrain ps = new crudTerrain();
        List<Terrain> terrains= ps.displayTerrains();
       File pdfFile = new File ("terrains.pdf");

        PdfWriter.getInstance(document, new FileOutputStream (pdfFile));
        document.open();
        document.addTitle("Terrains");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Aura");
        document.addCreator("Aura admin");
        Paragraph preface = new Paragraph();

        Paragraph titre =new Paragraph (" Aura Terrains");
        titre.setAlignment (Element.ALIGN_CENTER);

        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date ()));
        preface.add(new Paragraph(
                "This document contains all the terrains "));
        preface.setAlignment (Element.ALIGN_CENTER);
        document.add (titre);
        document.add(preface);
      
        // Start a new page
//        document.newPage();

        PDFTerrain pdf=new PDFTerrain ();
        PdfPTable table = new PdfPTable(5);

        PdfPCell c1 = new PdfPCell(new Phrase("ID"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Adresse"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Surface"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Potentiel"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("ID partenaire"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        

       

        table.setHeaderRows(1);
        for (Terrain t:terrains) {
            table.addCell(String.valueOf (t.getId_terrain()));
            table.addCell(String.valueOf (t.getAdresse()));
            table.addCell(String.valueOf (t.getSurface()));
            table.addCell(String.valueOf (t.getPotentiel()));
            table.addCell(String.valueOf (t.getId_membre()));
        }

        document.add (table);
        document.close ();
System.out.println("PDF file location: " + pdfFile.getAbsolutePath());

 }
  
}

